#markdown: rdiscount
markdown: kramdown
permalink: /:year/:month/:day/:title.html
url: http://www.ap0dom.com
name: "blog | cap0dom"
author: "cap0dom"
highlighter: pygments
safe: true
paginate: 16
auto: true
